spring.application.name=iot-device-command-service
server.port=8081

# Command execution config
command.max-retries=2
command.scheduler.rate=5000

# H2 in-memory database (dev only)
spring.datasource.url=jdbc:h2:mem:taskdb
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console